
typeset -U PATH path

if [ -d "~/.cargo" ]; then
  path=(~/.cargo/bin $path)
fi

export PATH

export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"

export GPG_TTY=$(tty)
unset SSH_AGENT_PID
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

export RANGER_LOAD_DEFAULT_RC=FALSE

export TASKRC=~/dotfiles/task/taskrc
export TASKDATA=~/documents/task
export TIMEWARRIORDB=~/documents/time

export QT_QPA_PLATFORMTHEME=qt5ct

